### ISSUE TITLE
Exception when using --files

### ISSUE THREAD

**Issue by SrikanthTati** [SingularitiesCR/spark-docker#4]
Hi,

I'm trying a sample app where a config file has to be shared using --files option. I see an exception when I use this

`./bin/spark-submit --files some-properties-file.conf --class org.apache.spark.examples.SparkPi --master local[2] ./examples/jars/spark-examples_2.11-2.0.1.jar 10`

Full exception stack below. Not sure what is causing this.

> Exception in thread "main" java.lang.IllegalArgumentException: Malformed IPv6 address at index 8: hdfs://[NAMENODE_HOST]:8020
>         at java.net.URI.create(URI.java:852)
>         at org.apache.hadoop.fs.FileSystem.getDefaultUri(FileSystem.java:180)
>         at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:361)
>         at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
>         at org.apache.spark.SparkContext.addFile(SparkContext.scala:1428)
>         at org.apache.spark.SparkContext.addFile(SparkContext.scala:1401)
>         at org.apache.spark.SparkContext$$anonfun$12.apply(SparkContext.scala:458)
>         at org.apache.spark.SparkContext$$anonfun$12.apply(SparkContext.scala:458)
>         at scala.collection.immutable.List.foreach(List.scala:381)
>         at org.apache.spark.SparkContext.<init>(SparkContext.scala:458)
>         at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2275)
>         at org.apache.spark.sql.SparkSession$Builder$$anonfun$8.apply(SparkSession.scala:831)
>         at org.apache.spark.sql.SparkSession$Builder$$anonfun$8.apply(SparkSession.scala:823)
>         at scala.Option.getOrElse(Option.scala:121)
>         at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:823)
>         at org.apache.spark.examples.SparkPi$.main(SparkPi.scala:31)
>         at org.apache.spark.examples.SparkPi.main(SparkPi.scala)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
>         at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
>         at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
>         at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
>         at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Caused by: java.net.URISyntaxException: Malformed IPv6 address at index 8: hdfs://[NAMENODE_HOST]:8020
>         at java.net.URI$Parser.fail(URI.java:2848)
>         at java.net.URI$Parser.parseIPv6Reference(URI.java:3469)
>         at java.net.URI$Parser.parseServer(URI.java:3219)
>         at java.net.URI$Parser.parseAuthority(URI.java:3155)
>         at java.net.URI$Parser.parseHierarchical(URI.java:3097)
>         at java.net.URI$Parser.parse(URI.java:3053)
>         at java.net.URI.<init>(URI.java:588)
>         at java.net.URI.create(URI.java:850)
>

**Comment by fjhoelsg** [comment]
Hi @SrikanthTati,

Did you run the provided startup scripts for Hadoop and Spark? There are placeholders in `core-site.xml` that must be replaced; otherwise, you will not be able to run Spark since it will try to connect to `hdfs://[NAMENODE_HOST]:8020`.

If you want to connect to the cluster and run jobs manually I would recommend starting the cluster first (probably using the example Docker Compose config) and then connecting via `docker exec`.

**Comment by SrikanthTati** [comment]
Hey @fjhoelsg,

I did use the start up script and its run using docker compose similar to what is mentioned in README.
And another container in the same compose that does _"spark-submit  --master spark://master:7077 ...."_
I know compose file is setup correctly. Any spark-submit w/o --files works fine.

So "_start-spark master_" starts spark master and namenode (_start-hadoop namenode daemon_)
and start-spark worker master" starts worker and datanode(_start-hadoop datanode $2 daemon_).

The part I might be missing is to update core-site.xml. Do you have a description on why/how/where to update it? Do I have to build another image after updating?

**Comment by fjhoelsg** [comment]
You can update the `core-site.xml` in `$HADOOP_CONF_DIR/core-site.xml`, which I believe expands to  `/usr/local/hadoop-2.7.3/etc/hadoop/core-site.xml` for the current version. In line 20 of that file the value for `fs.defaultFS` reads:

```
<value>hdfs://[NAMENODE_HOST]:8020</value>
```

Changing the placeholder should take care of the exception. Try it out and let me know if you are able to submit jobs.

**Comment by SrikanthTati** [comment]
Ah, that was it.

I was starting master and worker using the script. I was also starting a third container based on singularities/spark that does spark-submit. This container wasn't running the script(it is not a worker).

I'm thinking of adding this one extra command for the spark-submit container.

> sed -i.bak "s|\[NAMENODE_HOST\]|${1}|g" $HADOOP_CONF_DIR/core-site.xml

Is there anything else I may have to take care of?

**Comment by fjhoelsg** [comment]
No, I believe that's it. If you have any issues regarding permissions check [the script we use to start the Hadoop Namenode](https://github.com/SingularitiesCR/hadoop-docker/blob/master/start-hadoop-namenode).

If the issue is fixed please close it and feel free to open another issue if you encounter a different problem.

**Comment by SrikanthTati** [comment]
Thanks for the quick response!!
