### ISSUE TITLE
CPU Allocation

### ISSUE THREAD

**Issue by Naramsim** [SingularitiesCR/spark-docker#6]
Hi, how does spark-docker handles CPU allocation? When we create 3 workers, does the three workers work on different CPUs, or they use 3 CPUs in a shared way?

I've noticed that the more workers I use the slower the computation is. I'm using Docker 17 with 5 CPU and 5 Gb of RAM.

**Comment by fjhoelsg** [comment]
I believe that by default CPUs are shared among the containers. Regardless, if you wish to distribute the CPU's in a different way you should use the flags like `--cpuset` (if you are [running the containers via `docker run`](https://docs.docker.com/engine/reference/run/)) or the [Resources](https://docs.docker.com/compose/compose-file/#resources) field (if you are using Docker Compose).
